# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import fend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tittle', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(verbose_name=b'date created')),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyBalanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_user_name', models.CharField(max_length=100)),
                ('deposit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('price_start_date', models.DateTimeField(verbose_name=b'start date')),
                ('price_end_date', models.DateTimeField(verbose_name=b'end date')),
                ('created_date', models.DateTimeField(verbose_name=b'date created')),
            ],
        ),
        migrations.CreateModel(
            name='Mydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=200)),
                ('my_user_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name=b'date created')),
                ('smoke_status', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=2, null=True)),
                ('sick_type', models.CharField(max_length=10, null=True)),
                ('life_status', models.CharField(max_length=10, null=True)),
                ('ICDO3', models.IntegerField(default=0)),
                ('patho_status', models.CharField(max_length=5, null=True)),
                ('data_des', models.CharField(max_length=200, null=True)),
                ('genome_file', models.FileField(null=True, upload_to=fend.models.user_directory_path)),
                ('meth_file', models.FileField(null=True, upload_to=fend.models.user_directory_path)),
                ('micro_file', models.FileField(null=True, upload_to=fend.models.user_directory_path)),
                ('mRNA_file', models.FileField(null=True, upload_to=fend.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='MyDataQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_user_name', models.CharField(max_length=100)),
                ('mydata_id', models.IntegerField()),
                ('data_name', models.CharField(max_length=200)),
                ('smoke_status', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=2, null=True)),
                ('sick_type', models.CharField(max_length=10, null=True)),
                ('life_status', models.CharField(max_length=10, null=True)),
                ('ICDO3', models.IntegerField(default=0)),
                ('patho_status', models.CharField(max_length=5, null=True)),
                ('created_date', models.DateTimeField(verbose_name=b'date created')),
                ('genome_file', models.CharField(max_length=256)),
                ('status_id', models.IntegerField(default=0)),
                ('query_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_user_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name=b'date created')),
                ('phone', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
