# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=200)),
                ('query_type', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='LoadedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('file_type', models.IntegerField(default=0)),
                ('uploaded_date', models.DateTimeField(verbose_name='date uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='loadeddata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kopdata.Project'),
        ),
        migrations.AddField(
            model_name='createdquery',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kopdata.Project'),
        ),
    ]
