# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kopdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=200)),
                ('my_user_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('smoke_status', models.IntegerField(default=0)),
                ('is_man', models.BooleanField()),
                ('sick_type', models.IntegerField(default=0)),
                ('life_status', models.IntegerField(default=0)),
                ('ICDO3', models.IntegerField(default=0)),
                ('patho_status', models.IntegerField(default=0)),
                ('data_des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyDataQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=200)),
                ('query_type', models.IntegerField(default=0)),
                ('option_type', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('mydata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kopdata.Mydata')),
            ],
        ),
        migrations.CreateModel(
            name='MyLoadedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.IntegerField(default=0)),
                ('uploaded_date', models.DateTimeField(verbose_name='date uploaded')),
                ('mydata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kopdata.Mydata')),
            ],
        ),
        migrations.RemoveField(
            model_name='createdquery',
            name='project',
        ),
        migrations.RemoveField(
            model_name='loadeddata',
            name='project',
        ),
        migrations.DeleteModel(
            name='CreatedQuery',
        ),
        migrations.DeleteModel(
            name='LoadedData',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
