# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import kopdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('kopdata', '0002_auto_20160405_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_user_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('phone', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myloadeddata',
            name='mydata',
        ),
        migrations.RemoveField(
            model_name='mydata',
            name='is_man',
        ),
        migrations.AddField(
            model_name='mydata',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mydata',
            name='genome_file',
            field=models.FileField(null=True, upload_to=kopdata.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='mydata',
            name='mRNA_file',
            field=models.FileField(null=True, upload_to=kopdata.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='mydata',
            name='meth_file',
            field=models.FileField(null=True, upload_to=kopdata.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='mydata',
            name='micro_file',
            field=models.FileField(null=True, upload_to=kopdata.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='data_des',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='life_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='patho_status',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='sick_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='smoke_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mydataquery',
            name='option_type',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mydataquery',
            name='query_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mydataquery',
            name='query_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='MyLoadedData',
        ),
    ]
